#!/usr/bin/env python3
"""Phase 4H/4I — General probability coherence audit (reports only)."""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any

import requests

BACKEND_ROOT = Path(__file__).resolve().parent.parent
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

import config
from api.main import app
from core.probability_coherence_audit import (
    DEFAULT_AUDIT_MATCHUPS,
    ROOT_CAUSE_COHERENT,
    ROOT_CAUSE_ODDS_BLEND,
    build_audit_row_from_predict_response,
    summarize_audit_rows,
)
from fastapi.testclient import TestClient

DEFAULT_LIVE_URL = "https://football-predictor-api-bq6h.onrender.com"
LIVE_SAMPLE_MATCHUPS = (
    ("Qatar", "Canada"),
    ("Brazil", "Morocco"),
    ("Argentina", "France"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit 1X2 vs xG/top_scores coherence.")
    parser.add_argument(
        "--markdown",
        default="reports/probability_coherence_audit.md",
        help="Markdown report path",
    )
    parser.add_argument(
        "--csv",
        default="reports/probability_coherence_audit.csv",
        help="CSV summary path",
    )
    parser.add_argument(
        "--live-url",
        default=DEFAULT_LIVE_URL,
        help="Render API base URL for optional live comparison",
    )
    parser.add_argument(
        "--skip-live",
        action="store_true",
        help="Skip live Render checks",
    )
    return parser.parse_args()


def _predict_local_with_config(
    client: TestClient,
    home: str,
    away: str,
    *,
    calibration_enabled: bool | None = None,
    odds_affect: bool | None = None,
) -> dict[str, Any]:
    old_cal = config.PROBABILITY_CALIBRATION_ENABLED
    old_odds = config.ODDS_AFFECT_PREDICTION
    try:
        if calibration_enabled is not None:
            config.PROBABILITY_CALIBRATION_ENABLED = calibration_enabled
        if odds_affect is not None:
            config.ODDS_AFFECT_PREDICTION = odds_affect
        return _predict_local(client, home, away)
    finally:
        config.PROBABILITY_CALIBRATION_ENABLED = old_cal
        config.ODDS_AFFECT_PREDICTION = old_odds


def _predict_local(client: TestClient, home: str, away: str) -> dict[str, Any]:
    response = client.post(
        "/api/predict",
        json={"home_team": home, "away_team": away, "neutral_ground": True},
    )
    response.raise_for_status()
    return response.json()


def _predict_live(base_url: str, home: str, away: str) -> dict[str, Any]:
    response = requests.post(
        f"{base_url.rstrip('/')}/api/predict",
        json={"home_team": home, "away_team": away, "neutral_ground": True},
        timeout=45,
    )
    response.raise_for_status()
    return response.json()


def _simulate_odds_blend_row(home: str, away: str, payload: dict[str, Any]) -> dict[str, Any]:
    """Scenario B helper: show what odds-on blending would do without changing live code."""
    from core.odds_ensemble import blend_1x2

    pd = payload.get("probability_diagnostics") or {}
    raw = dict(pd.get("raw_probabilities_1x2") or payload.get("probabilities_1x2") or {})
    market = pd.get("market_probabilities_1x2")
    if not market:
        market = {
            "home_win": max(10.0, raw.get("away_win", 33.0)),
            "draw": raw.get("draw", 25.0),
            "away_win": max(10.0, raw.get("home_win", 33.0)),
        }
    blended = blend_1x2(raw, market)
    simulated = dict(payload)
    simulated["probabilities_1x2"] = blended
    simulated_pd = dict(pd)
    simulated_pd["raw_probabilities_1x2"] = raw
    simulated_pd["final_probabilities_1x2"] = blended
    simulated_pd["market_probabilities_1x2"] = market
    simulated_pd["odds_available"] = True
    simulated_pd["odds_affect_prediction"] = True
    simulated_pd["odds_blend_applied"] = True
    simulated["probability_diagnostics"] = simulated_pd
    return simulated


def _render_markdown(
    rows: list,
    summary: dict[str, Any],
    *,
    odds_affect_prediction: bool,
    calibration_enabled: bool,
) -> str:
    lines = [
        "# Probability Coherence Audit",
        "",
        "Generated by `scripts/audit_probability_coherence.py` (Phase 4H/4I).",
        "Diagnostic only — calibration activation remains blocked by default.",
        "",
        f"- Local `ODDS_AFFECT_PREDICTION`: **{odds_affect_prediction}**",
        f"- Local `PROBABILITY_CALIBRATION_ENABLED`: **{calibration_enabled}**",
        "",
        "## Executive summary",
        "",
        f"- Matchups audited: **{summary['total']}**",
        f"- Coherent: **{summary['coherent']}**",
        f"- Advisory only: **{summary['advisory']}**",
        f"- Blocking mismatches: **{summary['blocking']}**",
        f"- Top repeated root cause: `{summary['top_root_cause']}`",
        "",
        "### Root cause counts",
        "",
    ]
    for cause, count in sorted(summary["root_cause_counts"].items()):
        lines.append(f"- `{cause}`: {count}")
    lines.extend(["", "## Scenario notes", ""])
    lines.append(
        "- **local_odds_off**: current branch with `ODDS_AFFECT_PREDICTION=false` (default)."
    )
    lines.append(
        "- **local_simulated_odds_on**: same model output with synthetic/real market 70/30 blend applied for comparison."
    )
    lines.append(
        "- **local_calibration_on**: calibration enabled locally (Qatar/Canada regression pair only)."
    )
    lines.extend(["", "## Matchup table", ""])
    lines.append(
        "| Scenario | Match | 1X2 fav | xG fav | Top score | Blend | Gate | Root cause |"
    )
    lines.append("|----------|-------|---------|--------|-----------|-------|------|------------|")
    for row in rows:
        matchup = f"{row.home_team} vs {row.away_team}"
        lines.append(
            f"| {row.scenario} | {matchup} | {row.favorite_from_final_1x2 or '-'} | "
            f"{row.favorite_from_xg or '-'} | {row.favorite_from_top_score or '-'} | "
            f"{'yes' if row.odds_blend_applied else 'no'} | "
            f"{'PASS' if row.gate_passed else 'FAIL'} | {row.likely_root_cause} |"
        )
    lines.extend(["", "## Detailed findings", ""])
    for row in rows:
        lines.extend(
            [
                f"### {row.scenario}: {row.home_team} vs {row.away_team}",
                "",
                f"- Raw 1X2: `{json.dumps(row.raw_probabilities_1x2, ensure_ascii=False)}`",
                f"- Final 1X2: `{json.dumps(row.final_probabilities_1x2, ensure_ascii=False)}`",
                f"- xG: {row.home_xg:.2f} vs {row.away_xg:.2f}",
                f"- Top score: `{row.top_scores[0]['score'] if row.top_scores else 'n/a'}`",
                f"- Warnings: `{';'.join(row.coherence_warnings) or 'none'}`",
                f"- Gate blocking: `{';'.join(row.gate_blocking) or 'none'}`",
                f"- Gate advisory: `{';'.join(row.gate_advisory) or 'none'}`",
                f"- Likely root cause: `{row.likely_root_cause}`",
                "",
            ]
        )
    lines.extend(
        [
            "## Interpretation guide",
            "",
            "- Mismatch **without** odds blend locally → matrix/xG coherence issue or naturally close match.",
            "- Mismatch **only** in simulated/live odds-on scenario → odds blend is the likely root cause.",
            "- Mobile mapping uses `home_win`→home team and `away_win`→away team; score strings are home-away.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def _write_csv(path: Path, rows: list) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "scenario",
        "home_team",
        "away_team",
        "favorite_from_final_1x2",
        "favorite_from_xg",
        "favorite_from_top_score",
        "odds_available",
        "odds_affect_prediction",
        "odds_blend_applied",
        "gate_passed",
        "likely_root_cause",
        "coherence_warnings",
        "gate_blocking",
        "gate_advisory",
        "raw_probabilities_1x2",
        "final_probabilities_1x2",
        "home_xg",
        "away_xg",
        "top_score",
    ]
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(
                {
                    "scenario": row.scenario,
                    "home_team": row.home_team,
                    "away_team": row.away_team,
                    "favorite_from_final_1x2": row.favorite_from_final_1x2,
                    "favorite_from_xg": row.favorite_from_xg,
                    "favorite_from_top_score": row.favorite_from_top_score,
                    "odds_available": row.odds_available,
                    "odds_affect_prediction": row.odds_affect_prediction,
                    "odds_blend_applied": row.odds_blend_applied,
                    "gate_passed": row.gate_passed,
                    "likely_root_cause": row.likely_root_cause,
                    "coherence_warnings": ";".join(row.coherence_warnings),
                    "gate_blocking": ";".join(row.gate_blocking),
                    "gate_advisory": ";".join(row.gate_advisory),
                    "raw_probabilities_1x2": json.dumps(row.raw_probabilities_1x2),
                    "final_probabilities_1x2": json.dumps(row.final_probabilities_1x2),
                    "home_xg": row.home_xg,
                    "away_xg": row.away_xg,
                    "top_score": row.top_scores[0]["score"] if row.top_scores else "",
                }
            )


def _print_table(rows: list) -> None:
    print(f"{'Scenario':<24} {'Match':<28} {'1X2':<5} {'xG':<5} {'Top':<5} {'Blend':<5} {'Gate':<5} Root")
    for row in rows:
        matchup = f"{row.home_team} vs {row.away_team}"[:27]
        print(
            f"{row.scenario:<24} {matchup:<28} "
            f"{(row.favorite_from_final_1x2 or '-'):<5} "
            f"{(row.favorite_from_xg or '-'):<5} "
            f"{(row.favorite_from_top_score or '-'):<5} "
            f"{'Y' if row.odds_blend_applied else 'N':<5} "
            f"{'PASS' if row.gate_passed else 'FAIL':<5} {row.likely_root_cause}"
        )


def main() -> int:
    args = parse_args()
    client = TestClient(app)
    rows = []

    for home, away in DEFAULT_AUDIT_MATCHUPS:
        local = _predict_local(client, home, away)
        rows.append(
            build_audit_row_from_predict_response(local, scenario="local_odds_off")
        )
        simulated = _simulate_odds_blend_row(home, away, local)
        rows.append(
            build_audit_row_from_predict_response(
                simulated, scenario="local_simulated_odds_on"
            )
        )
        if (home, away) in (("Qatar", "Canada"), ("Canada", "Qatar")):
            cal_on = _predict_local_with_config(
                client, home, away, calibration_enabled=True
            )
            rows.append(
                build_audit_row_from_predict_response(
                    cal_on, scenario="local_calibration_on"
                )
            )

    if not args.skip_live:
        for home, away in LIVE_SAMPLE_MATCHUPS:
            try:
                live = _predict_live(args.live_url, home, away)
                rows.append(
                    build_audit_row_from_predict_response(live, scenario="live_render")
                )
            except Exception as exc:
                rows.append(
                    build_audit_row_from_predict_response(
                        {
                            "home_team": home,
                            "away_team": away,
                            "probabilities_1x2": {},
                            "home_xg": 0,
                            "away_xg": 0,
                            "top_scores": [],
                        },
                        scenario="live_render",
                    )
                )
                rows[-1].error = str(exc)

    summary = summarize_audit_rows(rows)
    md_path = Path(args.markdown)
    if not md_path.is_absolute():
        md_path = BACKEND_ROOT / md_path
    csv_path = Path(args.csv)
    if not csv_path.is_absolute():
        csv_path = BACKEND_ROOT / csv_path

    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(
        _render_markdown(
            rows,
            summary,
            odds_affect_prediction=config.ODDS_AFFECT_PREDICTION,
            calibration_enabled=config.PROBABILITY_CALIBRATION_ENABLED,
        ),
        encoding="utf-8",
    )
    _write_csv(csv_path, rows)
    _print_table(rows)
    print(f"\nWrote markdown report: {md_path}")
    print(f"Wrote CSV summary: {csv_path}")
    print(
        f"Summary: coherent={summary['coherent']} advisory={summary['advisory']} "
        f"blocking={summary['blocking']} top_root={summary['top_root_cause']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
