#!/usr/bin/env python3
"""Phase 4E — Walk-forward probability quality / calibration reports."""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from core.probability_quality import (
    ACTIVE_WALK_FORWARD_CONFIG,
    BASELINE_WALK_FORWARD_CONFIG,
    DEFAULT_QUALITY_DATASETS,
    evaluate_candidate_probability_quality,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate walk-forward probability calibration quality.",
    )
    parser.add_argument(
        "--datasets",
        default=",".join(DEFAULT_QUALITY_DATASETS),
        help="Comma-separated dataset keys (wc2018,wc2022,euro2024,copa2024)",
    )
    parser.add_argument(
        "--candidate",
        default="both",
        choices=["baseline", "active", "both"],
        help="Which walk-forward candidate configuration to evaluate",
    )
    parser.add_argument(
        "--markdown",
        default="reports/probability_quality_report.md",
        help="Markdown report output path",
    )
    parser.add_argument(
        "--csv",
        default="reports/probability_quality_report.csv",
        help="CSV summary output path",
    )
    return parser.parse_args()


def _parse_datasets(raw: str) -> list[str]:
    return [item.strip() for item in raw.split(",") if item.strip()]


def _worst_bucket(buckets: list[dict]) -> dict | None:
    if not buckets:
        return None
    return max(buckets, key=lambda bucket: abs(float(bucket["calibration_gap"])))


def _render_markdown(results: list[dict]) -> str:
    lines = [
        "# Probability Quality Report",
        "",
        "Generated by `scripts/evaluate_probability_quality.py` (Phase 4E).",
        "Reports measure calibration only — no live prediction or calibrator changes.",
        "",
    ]
    for result in results:
        label = result["candidate_label"]
        overall = result["overall"]
        lines.extend(
            [
                f"## {label}",
                "",
                f"- Walk-forward config: `{result['walk_forward_config']}`",
                f"- Matches: **{overall['count']}**",
                f"- 1X2 accuracy: **{overall['accuracy_1x2']:.4f}**",
                f"- Brier: **{overall['brier']:.4f}**",
                f"- Log-loss: **{overall['log_loss']:.4f}**",
                f"- ECE: **{overall['ece']:.4f}**",
                "",
            ]
        )
        if overall["warnings"]:
            lines.append("### Warnings")
            lines.append("")
            for warning in overall["warnings"]:
                lines.append(f"- `{warning}`")
            lines.append("")

        lines.append("### Per dataset")
        lines.append("")
        lines.append("| Dataset | N | Accuracy | Brier | Log-loss | ECE |")
        lines.append("|---------|---|----------|-------|----------|-----|")
        for dataset, metrics in result["per_dataset"].items():
            lines.append(
                f"| {dataset} | {metrics['count']} | {metrics['accuracy_1x2']:.4f} | "
                f"{metrics['brier']:.4f} | {metrics['log_loss']:.4f} | {metrics['ece']:.4f} |"
            )
        lines.append("")

        worst = _worst_bucket(overall["buckets"])
        if worst:
            lines.extend(
                [
                    "### Worst reliability bucket (overall)",
                    "",
                    f"- Bucket `{worst['bucket']}`: count={worst['count']}, "
                    f"avg_conf={worst['average_confidence']:.4f}, "
                    f"empirical={worst['empirical_accuracy']:.4f}, "
                    f"gap={worst['calibration_gap']:.4f}",
                    "",
                ]
            )

        lines.append("### Reliability buckets (overall)")
        lines.append("")
        lines.append("| Bucket | Count | Avg conf | Empirical | Gap | Avg Brier |")
        lines.append("|--------|-------|----------|-----------|-----|-----------|")
        for bucket in overall["buckets"]:
            lines.append(
                f"| {bucket['bucket']} | {bucket['count']} | {bucket['average_confidence']:.4f} | "
                f"{bucket['empirical_accuracy']:.4f} | {bucket['calibration_gap']:.4f} | "
                f"{bucket['average_brier']:.4f} |"
            )
        lines.append("")

        lines.append("### Favorite buckets (overall)")
        lines.append("")
        if overall["favorite_buckets"]:
            lines.append("| Bucket | Count | Avg conf | Empirical | Gap |")
            lines.append("|--------|-------|----------|-----------|-----|")
            for bucket in overall["favorite_buckets"]:
                lines.append(
                    f"| {bucket['bucket']} | {bucket['count']} | {bucket['average_confidence']:.4f} | "
                    f"{bucket['empirical_accuracy']:.4f} | {bucket['calibration_gap']:.4f} |"
                )
        else:
            lines.append("_No favorite buckets with sufficient confidence._")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _write_csv(results: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "candidate",
        "dataset",
        "count",
        "accuracy_1x2",
        "brier",
        "log_loss",
        "ece",
        "warnings",
    ]
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for result in results:
            label = result["candidate_label"]
            for dataset, metrics in result["per_dataset"].items():
                writer.writerow(
                    {
                        "candidate": label,
                        "dataset": dataset,
                        "count": metrics["count"],
                        "accuracy_1x2": metrics["accuracy_1x2"],
                        "brier": metrics["brier"],
                        "log_loss": metrics["log_loss"],
                        "ece": metrics["ece"],
                        "warnings": ";".join(metrics.get("warnings", [])),
                    }
                )
            overall = result["overall"]
            writer.writerow(
                {
                    "candidate": label,
                    "dataset": "OVERALL",
                    "count": overall["count"],
                    "accuracy_1x2": overall["accuracy_1x2"],
                    "brier": overall["brier"],
                    "log_loss": overall["log_loss"],
                    "ece": overall["ece"],
                    "warnings": ";".join(overall.get("warnings", [])),
                }
            )


def main() -> int:
    args = parse_args()
    datasets = _parse_datasets(args.datasets)
    results: list[dict] = []

    if args.candidate in ("baseline", "both"):
        results.append(
            evaluate_candidate_probability_quality(
                datasets,
                candidate_label="baseline",
                walk_forward_config=BASELINE_WALK_FORWARD_CONFIG,
            )
        )
    if args.candidate in ("active", "both"):
        results.append(
            evaluate_candidate_probability_quality(
                datasets,
                candidate_label="active_fifa_points",
                walk_forward_config=ACTIVE_WALK_FORWARD_CONFIG,
            )
        )

    md_path = Path(args.markdown)
    if not md_path.is_absolute():
        md_path = BACKEND_ROOT / md_path
    csv_path = Path(args.csv)
    if not csv_path.is_absolute():
        csv_path = BACKEND_ROOT / csv_path

    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(_render_markdown(results), encoding="utf-8")
    _write_csv(results, csv_path)

    print(f"Wrote markdown report: {md_path}")
    print(f"Wrote CSV summary: {csv_path}")
    for result in results:
        overall = result["overall"]
        print(
            f"{result['candidate_label']}: n={overall['count']} "
            f"acc={overall['accuracy_1x2']:.4f} brier={overall['brier']:.4f} "
            f"logloss={overall['log_loss']:.4f} ece={overall['ece']:.4f}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
