#!/usr/bin/env python3
"""Phase 4F — Shadow probability calibrator evaluation (reports only)."""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from core.probability_calibration import (
    fit_calibrator,
    overall_recommendation,
    pick_best_shadow_calibrator,
    search_shadow_calibrators,
)
from core.probability_quality import (
    ACTIVE_WALK_FORWARD_CONFIG,
    BASELINE_WALK_FORWARD_CONFIG,
    DEFAULT_QUALITY_DATASETS,
    collect_walk_forward_probability_rows,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate shadow probability calibrators on walk-forward rows.",
    )
    parser.add_argument(
        "--datasets",
        default=",".join(DEFAULT_QUALITY_DATASETS),
        help="Comma-separated dataset keys",
    )
    parser.add_argument(
        "--candidate",
        default="active",
        choices=["baseline", "active", "both"],
        help="Walk-forward probability source",
    )
    parser.add_argument(
        "--markdown",
        default="reports/probability_calibrators_report.md",
        help="Markdown report path",
    )
    parser.add_argument(
        "--csv",
        default="reports/probability_calibrators_report.csv",
        help="CSV summary path",
    )
    return parser.parse_args()


def _parse_datasets(raw: str) -> list[str]:
    return [item.strip() for item in raw.split(",") if item.strip()]


def _collect_rows(label: str, datasets: list[str]) -> tuple[str, list]:
    if label == "baseline":
        config = BASELINE_WALK_FORWARD_CONFIG
    else:
        config = ACTIVE_WALK_FORWARD_CONFIG
    rows = []
    for dataset in datasets:
        rows.extend(collect_walk_forward_probability_rows(dataset, **config))
    return label, rows


def _calibrator_label(result) -> str:
    if result.calibrator_name == "identity":
        return "uncalibrated"
    params = ", ".join(f"{k}={v}" for k, v in sorted(result.params.items()))
    return f"{result.calibrator_name}({params})"


def _render_markdown(sections: list[dict]) -> str:
    lines = [
        "# Shadow Probability Calibrators Report",
        "",
        "Generated by `scripts/evaluate_probability_calibrators.py` (Phase 4F).",
        "Shadow evaluation only — **no live prediction or production calibrator enabled**.",
        "",
        "Sample size note: walk-forward rows are limited (~211 matches).",
        "Bucket smoothing and isotonic calibrators deferred (small-sample / no sklearn).",
        "",
    ]
    for section in sections:
        source_label = section["source_label"]
        rows = section["rows"]
        results = section["results"]
        recommendation = section["recommendation"]
        best = section["best"]
        before = results[0].metrics_before

        lines.extend([f"## Source: {source_label}", "", "### Uncalibrated", ""])
        lines.append(f"- Matches: **{before['count']}**")
        lines.append(f"- Accuracy: **{before['accuracy_1x2']:.4f}**")
        lines.append(f"- Brier: **{before['brier']:.4f}**")
        lines.append(f"- Log-loss: **{before['log_loss']:.4f}**")
        lines.append(f"- ECE: **{before['ece']:.4f}**")
        lines.append("")
        lines.append("### Calibrator comparison")
        lines.append("")
        lines.append(
            "| Calibrator | Pass | Acc | Brier | Log-loss | ECE | ΔECE | ΔBrier |"
        )
        lines.append("|------------|------|-----|-------|----------|-----|------|--------|")
        for result in results:
            after = result.metrics_after
            delta_ece = before["ece"] - after["ece"]
            delta_brier = after["brier"] - before["brier"]
            passed = "yes" if result.passed_guardrails else "no"
            lines.append(
                f"| {_calibrator_label(result)} | {passed} | {after['accuracy_1x2']:.4f} | "
                f"{after['brier']:.4f} | {after['log_loss']:.4f} | {after['ece']:.4f} | "
                f"{delta_ece:+.4f} | {delta_brier:+.4f} |"
            )
        lines.append("")

        fitted_temp = fit_calibrator(rows, "temperature")
        fitted_shrink = fit_calibrator(rows, "favorite_shrink")
        lines.extend(
            [
                "### Fitted parameters (in-sample grid search)",
                "",
                f"- Best temperature (min log-loss): **{fitted_temp.params['temperature']}**",
                f"- Best favorite-shrink alpha (ECE-focused): **{fitted_shrink.params['alpha']}**",
                "",
            ]
        )

        if best is not None:
            after = best.metrics_after
            lines.extend(
                [
                    "### Best calibrator under guardrails",
                    "",
                    f"- **{_calibrator_label(best)}**",
                    f"- Accuracy: {after['accuracy_1x2']:.4f}",
                    f"- Brier: {after['brier']:.4f}",
                    f"- Log-loss: {after['log_loss']:.4f}",
                    f"- ECE: {after['ece']:.4f}",
                    "",
                ]
            )
            if best.failure_reasons:
                lines.append("Failure reasons for non-passing calibrators are in CSV.")
                lines.append("")
        else:
            lines.extend(
                [
                    "### Best calibrator under guardrails",
                    "",
                    "_None passed guardrails._",
                    "",
                ]
            )

        worst_before = max(before.get("buckets", []), key=lambda b: abs(b["calibration_gap"]), default=None)
        if best is not None:
            worst_after = max(
                best.metrics_after.get("buckets", []),
                key=lambda b: abs(b["calibration_gap"]),
                default=None,
            )
            lines.append("### Bucket calibration gap (worst bucket)")
            lines.append("")
            if worst_before:
                lines.append(
                    f"- Before: `{worst_before['bucket']}` gap={worst_before['calibration_gap']:.4f}"
                )
            if worst_after:
                lines.append(
                    f"- After (best): `{worst_after['bucket']}` gap={worst_after['calibration_gap']:.4f}"
                )
            lines.append("")

        if before.get("warnings"):
            lines.append("### Uncalibrated warnings")
            lines.append("")
            for warning in before["warnings"]:
                lines.append(f"- `{warning}`")
            lines.append("")

        lines.extend([f"### Recommendation: `{recommendation}`", "", ""])

    return "\n".join(lines).rstrip() + "\n"


def _write_csv(path: Path, sections: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "source",
        "calibrator",
        "params",
        "passed_guardrails",
        "accuracy",
        "brier",
        "log_loss",
        "ece",
        "delta_ece",
        "delta_brier",
        "recommendation",
        "failure_reasons",
    ]
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for section in sections:
            source = section["source_label"]
            recommendation = section["recommendation"]
            before_ece = section["results"][0].metrics_before["ece"]
            before_brier = section["results"][0].metrics_before["brier"]
            for result in section["results"]:
                after = result.metrics_after
                writer.writerow(
                    {
                        "source": source,
                        "calibrator": result.calibrator_name,
                        "params": str(result.params),
                        "passed_guardrails": result.passed_guardrails,
                        "accuracy": after["accuracy_1x2"],
                        "brier": after["brier"],
                        "log_loss": after["log_loss"],
                        "ece": after["ece"],
                        "delta_ece": round(before_ece - after["ece"], 4),
                        "delta_brier": round(after["brier"] - before_brier, 4),
                        "recommendation": recommendation,
                        "failure_reasons": ";".join(result.failure_reasons),
                    }
                )


def main() -> int:
    args = parse_args()
    datasets = _parse_datasets(args.datasets)
    labels = []
    if args.candidate in ("baseline", "both"):
        labels.append("baseline")
    if args.candidate in ("active", "both"):
        labels.append("active_fifa_points")

    sections: list[dict] = []
    for label in labels:
        walk_label = "baseline" if label == "baseline" else "active"
        _, rows = _collect_rows(walk_label, datasets)
        results = search_shadow_calibrators(rows)
        best = pick_best_shadow_calibrator(results)
        recommendation = overall_recommendation(rows, results)
        sections.append(
            {
                "source_label": label,
                "rows": rows,
                "results": results,
                "best": best,
                "recommendation": recommendation,
            }
        )

    md_path = Path(args.markdown)
    if not md_path.is_absolute():
        md_path = BACKEND_ROOT / md_path
    csv_path = Path(args.csv)
    if not csv_path.is_absolute():
        csv_path = BACKEND_ROOT / csv_path

    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(_render_markdown(sections), encoding="utf-8")
    _write_csv(csv_path, sections)

    print(f"Wrote markdown report: {md_path}")
    print(f"Wrote CSV summary: {csv_path}")
    for section in sections:
        before = section["results"][0].metrics_before
        best = section["best"]
        print(
            f"{section['source_label']}: uncalibrated ece={before['ece']:.4f} "
            f"brier={before['brier']:.4f} -> recommendation={section['recommendation']}"
        )
        if best is not None:
            after = best.metrics_after
            print(
                f"  best: {_calibrator_label(best)} ece={after['ece']:.4f} "
                f"brier={after['brier']:.4f}"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
