#!/usr/bin/env python3
"""Phase 4G — Out-of-sample calibration validation (reports only)."""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from core.probability_calibration import TemperatureCalibrator
from core.probability_calibration_validation import (
    FIXED_PHASE4F_TEMPERATURE,
    RECOMMENDATION_SHADOW_VALIDATED,
    SELECTION_CRITERION,
    fixed_candidate_validation,
    group_rows_by_dataset,
    leave_one_dataset_out_validation,
    summarize_validation_results,
)
from core.probability_quality import (
    ACTIVE_WALK_FORWARD_CONFIG,
    BASELINE_WALK_FORWARD_CONFIG,
    DEFAULT_QUALITY_DATASETS,
    collect_walk_forward_probability_rows,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate probability calibrators with holdout / LOO evaluation.",
    )
    parser.add_argument(
        "--datasets",
        default=",".join(DEFAULT_QUALITY_DATASETS),
        help="Comma-separated dataset keys",
    )
    parser.add_argument(
        "--candidate",
        default="active",
        choices=["baseline", "active", "both"],
        help="Walk-forward probability source",
    )
    parser.add_argument(
        "--mode",
        default="both",
        choices=["leave-one-dataset-out", "fixed", "both"],
        help="Validation mode",
    )
    parser.add_argument(
        "--markdown",
        default="reports/probability_calibration_validation.md",
        help="Markdown report path",
    )
    parser.add_argument(
        "--csv",
        default="reports/probability_calibration_validation.csv",
        help="CSV summary path",
    )
    return parser.parse_args()


def _parse_datasets(raw: str) -> list[str]:
    return [item.strip() for item in raw.split(",") if item.strip()]


def _collect_rows_by_dataset(label: str, datasets: list[str]) -> tuple[str, dict[str, list]]:
    config = BASELINE_WALK_FORWARD_CONFIG if label == "baseline" else ACTIVE_WALK_FORWARD_CONFIG
    rows_by_dataset: dict[str, list] = {}
    for dataset in datasets:
        rows = collect_walk_forward_probability_rows(dataset, **config)
        rows_by_dataset[dataset] = rows
    return label, rows_by_dataset


def _fmt_calibrator(name: str, params: dict) -> str:
    if name == "identity":
        return "identity"
    parts = ", ".join(f"{k}={v}" for k, v in sorted(params.items()))
    return f"{name}({parts})"


def _fmt_bucket_line(label: str, bucket: dict | None) -> str:
    if not bucket:
        return f"- {label}: _none_"
    return (
        f"- {label}: `{bucket['bucket']}` gap={bucket['calibration_gap']:.4f} "
        f"(n={bucket['count']})"
    )


def _render_markdown(sections: list[dict]) -> str:
    lines = [
        "# Probability Calibration Validation Report",
        "",
        "Generated by `scripts/validate_probability_calibrators.py` (Phase 4G).",
        "Validation only — **no live prediction or production calibrator enabled**.",
        "",
        f"Train-fold selection criterion: `{SELECTION_CRITERION}`.",
        "Isotonic / bucket smoothing deferred (small-sample / no sklearn).",
        "",
    ]

    for section in sections:
        source = section["source_label"]
        summary = section["summary"]
        fixed = section.get("fixed_result")
        folds = section.get("folds", [])

        lines.extend(
            [
                f"## Source: {source}",
                "",
                f"### Executive summary: `{summary.executive_summary}`",
                "",
                f"### Recommendation: `{summary.recommendation}`",
                "",
            ]
        )

        if fixed is not None:
            before = fixed.combined_before
            after = fixed.combined_after
            lines.extend(
                [
                    "### Fixed Phase 4F candidate: temperature(T=1.35)",
                    "",
                    "| Metric | Before | After | Delta |",
                    "|--------|--------|-------|-------|",
                    f"| Accuracy | {before['accuracy_1x2']:.4f} | {after['accuracy_1x2']:.4f} | "
                    f"{after['accuracy_1x2'] - before['accuracy_1x2']:+.4f} |",
                    f"| Brier | {before['brier']:.4f} | {after['brier']:.4f} | "
                    f"{after['brier'] - before['brier']:+.4f} |",
                    f"| Log-loss | {before['log_loss']:.4f} | {after['log_loss']:.4f} | "
                    f"{after['log_loss'] - before['log_loss']:+.4f} |",
                    f"| ECE | {before['ece']:.4f} | {after['ece']:.4f} | "
                    f"{after['ece'] - before['ece']:+.4f} |",
                    "",
                    f"Guardrails: **{'PASS' if fixed.passed_guardrails else 'FAIL'}**",
                    "",
                ]
            )
            if fixed.failure_reasons:
                lines.append("Failure reasons:")
                for reason in fixed.failure_reasons:
                    lines.append(f"- `{reason}`")
                lines.append("")

            lines.append("#### Per-dataset (fixed T=1.35)")
            lines.append("")
            lines.append("| Dataset | Acc before | Acc after | Brier Δ | ECE Δ |")
            lines.append("|---------|------------|-----------|---------|-------|")
            for dataset in sorted(fixed.per_dataset_before.keys()):
                b = fixed.per_dataset_before[dataset]
                a = fixed.per_dataset_after[dataset]
                lines.append(
                    f"| {dataset} | {b['accuracy_1x2']:.4f} | {a['accuracy_1x2']:.4f} | "
                    f"{a['brier'] - b['brier']:+.4f} | {a['ece'] - b['ece']:+.4f} |"
                )
            lines.append("")

            buckets = fixed.bucket_analysis
            lines.append("#### Bucket analysis (fixed, combined)")
            lines.append("")
            lines.append(_fmt_bucket_line("Worst overconfident before", buckets.get("worst_overconfident_before")))
            lines.append(_fmt_bucket_line("Worst underconfident before", buckets.get("worst_underconfident_before")))
            lines.append(_fmt_bucket_line("Worst overconfident after", buckets.get("worst_overconfident_after")))
            lines.append(_fmt_bucket_line("Worst underconfident after", buckets.get("worst_underconfident_after")))
            lines.append("")

        if folds:
            combined_before = summary.combined_holdout_before or {}
            combined_after = summary.combined_holdout_after or {}
            lines.extend(
                [
                    "### Leave-one-dataset-out validation",
                    "",
                    f"Combined held-out matches: **{combined_before.get('count', 0)}**",
                    "",
                    "| Metric | Before | After | Delta |",
                    "|--------|--------|-------|-------|",
                    f"| Accuracy | {combined_before.get('accuracy_1x2', 0):.4f} | "
                    f"{combined_after.get('accuracy_1x2', 0):.4f} | "
                    f"{combined_after.get('accuracy_1x2', 0) - combined_before.get('accuracy_1x2', 0):+.4f} |",
                    f"| Brier | {combined_before.get('brier', 0):.4f} | "
                    f"{combined_after.get('brier', 0):.4f} | "
                    f"{combined_after.get('brier', 0) - combined_before.get('brier', 0):+.4f} |",
                    f"| Log-loss | {combined_before.get('log_loss', 0):.4f} | "
                    f"{combined_after.get('log_loss', 0):.4f} | "
                    f"{combined_after.get('log_loss', 0) - combined_before.get('log_loss', 0):+.4f} |",
                    f"| ECE | {combined_before.get('ece', 0):.4f} | "
                    f"{combined_after.get('ece', 0):.4f} | "
                    f"{combined_after.get('ece', 0) - combined_before.get('ece', 0):+.4f} |",
                    "",
                    f"Guardrails: **{'PASS' if summary.holdout_passed_guardrails else 'FAIL'}**",
                    "",
                ]
            )
            if summary.holdout_failure_reasons:
                lines.append("Failure reasons:")
                for reason in summary.holdout_failure_reasons:
                    lines.append(f"- `{reason}`")
                lines.append("")

            lines.append("#### Per-fold selections and held-out metrics")
            lines.append("")
            lines.append(
                "| Held out | Selected | Acc Δ | Brier Δ | ECE Δ | Fold guardrails |"
            )
            lines.append("|----------|----------|-------|---------|-------|-----------------|")
            for fold in folds:
                b = fold.metrics_before
                a = fold.metrics_after
                selected = _fmt_calibrator(fold.selected_calibrator, fold.selected_params)
                passed = "PASS" if fold.passed_guardrails else "FAIL"
                lines.append(
                    f"| {fold.held_out_dataset} | {selected} | "
                    f"{a['accuracy_1x2'] - b['accuracy_1x2']:+.4f} | "
                    f"{a['brier'] - b['brier']:+.4f} | {a['ece'] - b['ece']:+.4f} | {passed} |"
                )
            lines.append("")

            if summary.per_dataset_regressions:
                lines.append("#### Per-dataset regressions (combined holdout)")
                lines.append("")
                for item in summary.per_dataset_regressions:
                    lines.append(f"- `{item}`")
                lines.append("")

            lines.append("#### Bucket analysis per held-out fold")
            lines.append("")
            for fold in folds:
                buckets = fold.bucket_analysis
                lines.append(f"**{fold.held_out_dataset}**")
                lines.append(_fmt_bucket_line("Worst overconfident before", buckets.get("worst_overconfident_before")))
                lines.append(_fmt_bucket_line("Worst underconfident before", buckets.get("worst_underconfident_before")))
                lines.append(_fmt_bucket_line("Worst overconfident after", buckets.get("worst_overconfident_after")))
                lines.append(_fmt_bucket_line("Worst underconfident after", buckets.get("worst_underconfident_after")))
                lines.append("")

        if summary.recommendation == RECOMMENDATION_SHADOW_VALIDATED:
            lines.extend(
                [
                    "### Next step",
                    "",
                    "Phase 4H may wire calibration behind `PROBABILITY_CALIBRATION_ENABLED=false` default.",
                    "",
                ]
            )
        else:
            lines.extend(
                [
                    "### Next step",
                    "",
                    "Keep calibration report-only; consider odds/coherence work or live tournament updates.",
                    "",
                ]
            )

    return "\n".join(lines).rstrip() + "\n"


def _write_csv(path: Path, sections: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "source",
        "validation_mode",
        "held_out_dataset",
        "selected_calibrator",
        "accuracy_before",
        "accuracy_after",
        "brier_before",
        "brier_after",
        "log_loss_before",
        "log_loss_after",
        "ece_before",
        "ece_after",
        "passed_guardrails",
        "executive_summary",
        "recommendation",
        "failure_reasons",
    ]
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for section in sections:
            source = section["source_label"]
            summary = section["summary"]
            fixed = section.get("fixed_result")
            if fixed is not None:
                b = fixed.combined_before
                a = fixed.combined_after
                writer.writerow(
                    {
                        "source": source,
                        "validation_mode": "fixed",
                        "held_out_dataset": "combined",
                        "selected_calibrator": fixed.calibrator_label,
                        "accuracy_before": b["accuracy_1x2"],
                        "accuracy_after": a["accuracy_1x2"],
                        "brier_before": b["brier"],
                        "brier_after": a["brier"],
                        "log_loss_before": b["log_loss"],
                        "log_loss_after": a["log_loss"],
                        "ece_before": b["ece"],
                        "ece_after": a["ece"],
                        "passed_guardrails": fixed.passed_guardrails,
                        "executive_summary": summary.executive_summary,
                        "recommendation": summary.recommendation,
                        "failure_reasons": ";".join(fixed.failure_reasons),
                    }
                )
            for fold in section.get("folds", []):
                b = fold.metrics_before
                a = fold.metrics_after
                writer.writerow(
                    {
                        "source": source,
                        "validation_mode": "leave-one-dataset-out",
                        "held_out_dataset": fold.held_out_dataset,
                        "selected_calibrator": _fmt_calibrator(
                            fold.selected_calibrator, fold.selected_params
                        ),
                        "accuracy_before": b["accuracy_1x2"],
                        "accuracy_after": a["accuracy_1x2"],
                        "brier_before": b["brier"],
                        "brier_after": a["brier"],
                        "log_loss_before": b["log_loss"],
                        "log_loss_after": a["log_loss"],
                        "ece_before": b["ece"],
                        "ece_after": a["ece"],
                        "passed_guardrails": fold.passed_guardrails,
                        "executive_summary": summary.executive_summary,
                        "recommendation": summary.recommendation,
                        "failure_reasons": ";".join(fold.failure_reasons),
                    }
                )


def main() -> int:
    args = parse_args()
    datasets = _parse_datasets(args.datasets)
    labels: list[str] = []
    if args.candidate in ("baseline", "both"):
        labels.append("baseline")
    if args.candidate in ("active", "both"):
        labels.append("active_fifa_points")

    sections: list[dict] = []
    for label in labels:
        walk_label = "baseline" if label == "baseline" else "active"
        _, rows_by_dataset = _collect_rows_by_dataset(walk_label, datasets)

        folds = None
        combined_before = None
        combined_after = None
        fixed_result = None

        if args.mode in ("leave-one-dataset-out", "both"):
            folds, combined_before, combined_after = leave_one_dataset_out_validation(
                rows_by_dataset
            )

        if args.mode in ("fixed", "both"):
            fixed_cal = TemperatureCalibrator(temperature=FIXED_PHASE4F_TEMPERATURE)
            fixed_result = fixed_candidate_validation(rows_by_dataset, fixed_cal)

        summary = summarize_validation_results(
            folds=folds,
            combined_holdout_before=combined_before,
            combined_holdout_after=combined_after,
            fixed_result=fixed_result,
        )
        sections.append(
            {
                "source_label": label,
                "summary": summary,
                "folds": folds or [],
                "fixed_result": fixed_result,
            }
        )

    md_path = Path(args.markdown)
    if not md_path.is_absolute():
        md_path = BACKEND_ROOT / md_path
    csv_path = Path(args.csv)
    if not csv_path.is_absolute():
        csv_path = BACKEND_ROOT / csv_path

    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(_render_markdown(sections), encoding="utf-8")
    _write_csv(csv_path, sections)

    print(f"Wrote markdown report: {md_path}")
    print(f"Wrote CSV summary: {csv_path}")
    for section in sections:
        s = section["summary"]
        print(
            f"{section['source_label']}: executive={s.executive_summary} "
            f"recommendation={s.recommendation}"
        )
        if section.get("fixed_result"):
            fr = section["fixed_result"]
            print(
                f"  fixed T=1.35: ece {fr.combined_before['ece']:.4f} -> "
                f"{fr.combined_after['ece']:.4f} guardrails={'PASS' if fr.passed_guardrails else 'FAIL'}"
            )
        if section.get("folds"):
            cb = s.combined_holdout_before or {}
            ca = s.combined_holdout_after or {}
            print(
                f"  LOO combined: ece {cb.get('ece', 0):.4f} -> {ca.get('ece', 0):.4f} "
                f"guardrails={'PASS' if s.holdout_passed_guardrails else 'FAIL'}"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
